@hostname = http://localhost:8080/api

###

POST {{hostname}}/users
Content-Type: application/json

{
  "userId": "testuser1",
  "phone": "010-2134-1534",
  "email": "testuser1@example.com",
  "username": "김윤성",
  "password": "qweQQ!!1",
  "role": 1
}

###

POST {{hostname}}/users
Content-Type: application/json

{
  "userId": "류니끄",
  "phone": "010-7894-5612",
  "email": "michelin@example.com",
  "username": "최태성",
  "password": "qweQQ!!1",
  "role": 2
}

###

PATCH {{hostname}}/users/me
Content-Type: application/json
Authorization: {{authToken}}

{
  "password": "qweQQ!!1"
}

###

# @name login
POST {{hostname}}/auth/login HTTP/1.1
Content-Type: application/json

# "userId": "testuser1",
# "userId": "류니끄",
{
  "userId": "testuser1",
  "password": "qweQQ!!1"
}

###

@authToken = Bearer {{login.response.body.payload.accessToken}}

###

# # @name refresh
# POST {{hostname}}/auth/refresh HTTP/1.1
# Content-Type: application/json
# Authorization: {{authToken}}

# ###

# @authToken = Bearer {{refresh.response.body.payload.accessToken}}

###

# getMe
GET {{hostname}}/users/me HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

###

# reservation(Customer)
POST {{hostname}}/restaurants/1/reservations HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
  "reserveStartAt": "2025-03-13 18:00",
  "reserveEndAt": "2025-03-13 18:30",
  "phone": "101-2234-5678",
  "amount": 5,
  "menu": [3]
}

###

POST {{hostname}}/restaurants HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
  "category": "fine dining",
  "name": "류니끄",
  "location": "서울 00구 00로00길 00 0층"
}

###

# 단일 추가
POST {{hostname}}/restaurants/1/menus HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
  "category": "main",
  "name": "봉골레 파스타",
  "description": "봉골레",
  "price": 50.020
}

###

# bulk 추가
POST {{hostname}}/restaurants/1/menus HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

[{
  "category": "side",
  "name": "리코타 치츠 샐러드",
  "description": "샐러드",
  "price": 15000
},{
  "category": "main",
  "name": "마르게리타 피자",
  "description": "피자",
  "price": -20000
}]

###

# 예약 조회
GET {{hostname}}/users/me/reservations HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

